export const themes: OneThemeI[] = [
  {
    id: 1,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2021/10/good-800x600.jpg",
    title: "Good – Bootstrap 5 Admin Dashboard Template",
    category: "Admin & Dashboard",
    section: "Latest",
    price: 49.0,
    rate: 0,
    link: "https://themes.getbootstrap.com/product/good-bootstrap-5-admin-dashboard-template/",
  },
  {
    id: 2,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2021/10/dashkit-react-screenshot-800x600.jpg",
    title: "Dashkit – Admin & Dashboard Template [React]",
    category: "Admin & Dashboard",
    section: "Latest",
    price: 49.0,
    rate: 0,
    link: "https://themes.getbootstrap.com/product/dashkit-admin-dashboard-template-react/",
  },
  {
    id: 3,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2019/03/falcon-v3.2.0-800x600.png",
    title: "Falcon – Admin Dashboard & WebApp Template",
    category: "Admin & Dashboard",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/falcon-admin-dashboard-webapp-template/",
  },
  {
    id: 4,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2018/07/hyper-shot-1200x900-3-800x600.png",
    title: "Hyper – Admin & Dashboard Template (Dark/Light)",
    category: "Admin & Dashboard",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/hyper-responsive-admin-dashboard-template/",
  },
  {
    id: 5,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2018/05/front-cover-min-800x600.jpeg",
    title: "Front – Multipurpose Responsive Template",
    category: "Landing & Corporate",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/front-multipurpose-responsive-template/",
  },
  {
    id: 6,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2018/09/screenshot2-bs5-800x600.jpg",
    title: "AppStack – Admin & Dashboard Template (Dark/Light)",
    category: "Admin & Dashboard",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/appstack-responsive-admin-template/",
  },
  {
    id: 7,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2019/09/react-falcon-800x600.png",
    title: "Falcon – Admin Dashboard & WebApp Template [React]",
    category: "Admin & Dashboard",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/falcon-admin-dashboard-webapp-template-react/",
  },
  {
    id: 8,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2019/10/screenshot-3-800x600.jpg",
    title: "Cartzilla – Multipurpose eCommerce Template",
    category: "E-Commerce & Retail",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/cartzilla-bootstrap-e-commerce-template-ui-kit/",
  },
  {
    id: 9,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2021/06/screenshot-800x600.jpg",
    title: "Finder – Directory & Listings Template + UI Kit",
    category: "E-Commerce & Retail",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/finder-directory-listings-template-ui-kit/",
  },
  {
    id: 10,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2018/06/dashkit-screenshot-crushed-800x600.jpg",
    title: "Dashkit – Admin & Dashboard Template (Dark/Light)",
    category: "E-Commerce & Retail",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/dashkit-admin-dashboard-template/",
  },
  {
    id: 11,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2018/07/cover-bs5-min-800x600.jpg",
    title: "Space – Multipurpose Template + UI Kit",
    category: "Landing & Corporate",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/space-multipurpose-responsive-template/",
  },
  {
    id: 12,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2020/08/front-dashboard-preview-1-800x600.jpg",
    title: "Front – Admin & Dashboard Template",
    category: "Admin & Dashboard",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/front-admin-dashboard-template/",
  },
  {
    id: 13,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2019/03/screenshot2-800x600.jpg",
    title: "AppStack – Admin & Dashboard Template [React]",
    category: "Admin & Dashboard",
    section: "Popular",
    price: 59.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/appstack-react-admin-dashboard-template/",
  },
  {
    id: 14,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2019/04/landkit-screenshot-v2.0.0-800x600.jpg",
    title: "Landkit – Multipurpose Template + UI Kit",
    category: "Landing & Corporate",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/landkit/",
  },
  {
    id: 15,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2021/01/Geeks-Bootstrap-5-Template-800x600.jpg",
    title: "Geeks Academy Admin Template",
    category: "Application",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/geeks-academy-admin-template/",
  },
  {
    id: 16,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2019/06/hyper-react-800x600.png",
    title: "Hyper React – Admin & Dashboard Template [ReactJS]",
    category: "Admin & Dashboard",
    section: "Popular",
    price: 59.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/hyper-react-admin-dashboard-template/",
  },
  {
    id: 17,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2021/02/cube-2-thumb-800x600.jpg",
    title: "Cube – Multipurpose Template + UI Kit",
    category: "Landing & Corporate",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/cube-multipurpose-template-ui-kit/",
  },
  {
    id: 18,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2018/04/Screen-Shot-2019-11-27-at-16.48.00-scaled-800x600.png",
    title: "Looper – Responsive Admin Template (Dark/Light)",
    category: "Admin & Dashboard",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/looper-responsive-admin-template/",
  },
  {
    id: 19,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2021/07/soft-ui-dashboard-pro-thumbnail-800x600.jpg",
    title: "Soft UI Dashboard Pro",
    category: "Admin & Dashboard",
    section: "Popular",
    price: 59.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/soft-ui-dashboard-pro/",
  },
  {
    id: 20,
    imgURL:
      "https://themes.getbootstrap.com/wp-content/uploads/2019/02/directory-b5-1200x900-800x600.jpg",
    title: "Directory – Directory & Listing Bootstrap 5 Theme",
    category: "E-Commerce & Retail",
    section: "Popular",
    price: 49.0,
    rate: 5,
    link: "https://themes.getbootstrap.com/product/directory-directory-listing-bootstrap-4-theme/",
  },
];
